import { Timestamp } from 'firebase/firestore';
import type { Place } from '@/types';

export const MOCK_PLACES: Place[] = [
  {
    id: 'mock_001',
    name: "Aling Rosa's Tapsilog",
    categories: ['silog'],
    description: 'Masarap na tapsilog na pang-umaga. Laging masabaw ang kanin!',
    priceMin: 65,
    priceMax: 85,
    latitude: 13.6218,
    longitude: 123.1948,
    address: 'Magsaysay Ave, Naga City',
    googleMapsUrl: 'https://maps.google.com/?q=13.6218,123.1948',
    photoUrl: undefined,
    likes: 24,
    createdBy: 'seed_admin',
    isSeeded: true,
    createdAt: Timestamp.now(),
  },
  {
    id: 'mock_002',
    name: "Ate Rica's Bacsilog",
    categories: ['silog'],
    description: 'Crispy na bacon silog. Sulit na sulit sa presyo!',
    priceMin: 55,
    priceMax: 75,
    latitude: 13.6230,
    longitude: 123.1960,
    address: 'Panganiban Drive, Naga City',
    googleMapsUrl: 'https://maps.google.com/?q=13.6230,123.1960',
    photoUrl: undefined,
    likes: 18,
    createdBy: 'seed_admin',
    isSeeded: true,
    createdAt: Timestamp.now(),
  },
  {
    id: 'mock_003',
    name: "Mang Larry's Isawan",
    categories: ['street-food', 'ihaw-ihaw'],
    description: 'Pinakamasarap na isaw sa Naga. Classic talaga!',
    priceMin: 10,
    priceMax: 30,
    latitude: 13.6200,
    longitude: 123.1935,
    address: 'SM City Naga, Naga City',
    googleMapsUrl: 'https://maps.google.com/?q=13.6200,123.1935',
    photoUrl: undefined,
    likes: 41,
    createdBy: 'seed_admin',
    isSeeded: true,
    createdAt: Timestamp.now(),
  },
  {
    id: 'mock_004',
    name: 'Tusok-Tusok sa Kanto',
    categories: ['street-food'],
    description: 'Fishball, squidball, kikiam — lahat nandito! Perfect meryenda.',
    priceMin: 5,
    priceMax: 20,
    latitude: 13.6245,
    longitude: 123.1970,
    address: 'Elias Angeles St, Naga City',
    googleMapsUrl: 'https://maps.google.com/?q=13.6245,123.1970',
    photoUrl: undefined,
    likes: 33,
    createdBy: 'seed_admin',
    isSeeded: true,
    createdAt: Timestamp.now(),
  },
  {
    id: 'mock_005',
    name: "Lola's Carinderia",
    categories: ['carinderia', 'turo-turo'],
    description: 'Lutong-bahay ang dating. Palagi may adobo at sinigang.',
    priceMin: 50,
    priceMax: 90,
    latitude: 13.6190,
    longitude: 123.1920,
    address: 'Triangulo, Naga City',
    googleMapsUrl: 'https://maps.google.com/?q=13.6190,123.1920',
    photoUrl: undefined,
    likes: 56,
    createdBy: 'seed_admin',
    isSeeded: true,
    createdAt: Timestamp.now(),
  },
  {
    id: 'mock_006',
    name: 'Kainan sa Palengke',
    categories: ['turo-turo', 'carinderia'],
    description: 'Turo-turo malapit sa palengke. Maraming pagpipilian araw-araw.',
    priceMin: 45,
    priceMax: 80,
    latitude: 13.6260,
    longitude: 123.1980,
    address: 'Central Market, Naga City',
    googleMapsUrl: 'https://maps.google.com/?q=13.6260,123.1980',
    photoUrl: undefined,
    likes: 29,
    createdBy: 'seed_admin',
    isSeeded: true,
    createdAt: Timestamp.now(),
  },
  {
    id: 'mock_007',
    name: 'Pancit Malabon Express',
    categories: ['merienda', 'carinderia'],
    description: 'Espesyal na pancit malabon. Subok na ng maraming henerasyon.',
    priceMin: 40,
    priceMax: 70,
    latitude: 13.6205,
    longitude: 123.1955,
    address: 'Almeda Highway, Naga City',
    googleMapsUrl: 'https://maps.google.com/?q=13.6205,123.1955',
    photoUrl: undefined,
    likes: 22,
    createdBy: 'seed_admin',
    isSeeded: true,
    createdAt: Timestamp.now(),
  },
  {
    id: 'mock_008',
    name: "Aling Banang's Halo-Halo",
    categories: ['merienda'],
    description: 'Pinaka-sikat na halo-halo sa buong Naga. Perfect sa tag-araw!',
    priceMin: 45,
    priceMax: 65,
    latitude: 13.6235,
    longitude: 123.1965,
    address: 'J. Miranda Ave, Naga City',
    googleMapsUrl: 'https://maps.google.com/?q=13.6235,123.1965',
    photoUrl: undefined,
    likes: 67,
    createdBy: 'seed_admin',
    isSeeded: true,
    createdAt: Timestamp.now(),
  },
  {
    id: 'mock_009',
    name: "Tatay Jun's Ihaw",
    categories: ['ihaw-ihaw', 'street-food'],
    description: 'Inihaw na liempo at manok. Mapapasarap ka talaga dito!',
    priceMin: 50,
    priceMax: 120,
    latitude: 13.6215,
    longitude: 123.1942,
    address: 'Roxas Ave, Naga City',
    googleMapsUrl: 'https://maps.google.com/?q=13.6215,123.1942',
    photoUrl: undefined,
    likes: 38,
    createdBy: 'seed_admin',
    isSeeded: true,
    createdAt: Timestamp.now(),
  },
  {
    id: 'mock_010',
    name: 'Turo-Turo sa Palengke',
    categories: ['turo-turo'],
    description: 'Mga ulam ng ina. Palaging may bagong lutuin.',
    priceMin: 40,
    priceMax: 75,
    latitude: 13.6270,
    longitude: 123.1990,
    address: 'Public Market, Naga City',
    googleMapsUrl: 'https://maps.google.com/?q=13.6270,123.1990',
    photoUrl: undefined,
    likes: 31,
    createdBy: 'seed_admin',
    isSeeded: true,
    createdAt: Timestamp.now(),
  },
  {
    id: 'mock_011',
    name: 'Potato Corner Naga',
    categories: ['street-food', 'merienda'],
    description: 'Classic flavored fries. Barbecue, cheese, sour cream!',
    priceMin: 35,
    priceMax: 60,
    latitude: 13.6198,
    longitude: 123.1928,
    address: 'SM City Naga, Naga City',
    googleMapsUrl: 'https://maps.google.com/?q=13.6198,123.1928',
    photoUrl: undefined,
    likes: 45,
    createdBy: 'seed_admin',
    isSeeded: true,
    createdAt: Timestamp.now(),
  },
  {
    id: 'mock_012',
    name: 'Master Siomai',
    categories: ['street-food'],
    description: 'Pork siomai na sulit. Libre ang toyo at calamansi!',
    priceMin: 15,
    priceMax: 40,
    latitude: 13.6250,
    longitude: 123.1975,
    address: 'Concepcion Pequeña, Naga City',
    googleMapsUrl: 'https://maps.google.com/?q=13.6250,123.1975',
    photoUrl: undefined,
    likes: 27,
    createdBy: 'seed_admin',
    isSeeded: true,
    createdAt: Timestamp.now(),
  },
  {
    id: 'mock_013',
    name: "Andok's Litson Manok",
    categories: ['ihaw-ihaw'],
    description: 'Golden crispy chicken na pang-pamilya. Libre ang sauce!',
    priceMin: 180,
    priceMax: 320,
    latitude: 13.6225,
    longitude: 123.1958,
    address: 'Diversion Road, Naga City',
    googleMapsUrl: 'https://maps.google.com/?q=13.6225,123.1958',
    photoUrl: undefined,
    likes: 52,
    createdBy: 'seed_admin',
    isSeeded: true,
    createdAt: Timestamp.now(),
  },
  {
    id: 'mock_014',
    name: 'Brew & Bites Coffee',
    categories: ['kape-inumin', 'merienda'],
    description: 'Budget-friendly local coffee at kasamang tinapay. Pang-araw!',
    priceMin: 40,
    priceMax: 90,
    latitude: 13.6240,
    longitude: 123.1950,
    address: 'Ateneo Ave, Naga City',
    googleMapsUrl: 'https://maps.google.com/?q=13.6240,123.1950',
    photoUrl: undefined,
    likes: 19,
    createdBy: 'seed_admin',
    isSeeded: true,
    createdAt: Timestamp.now(),
  },
  {
    id: 'mock_015',
    name: 'Jollibee Naga',
    categories: ['fastfood'],
    description: 'Chickenjoy at Yumburger. Laging paboritong fast food ng Pinoy.',
    priceMin: 69,
    priceMax: 180,
    latitude: 13.6210,
    longitude: 123.1945,
    address: 'Magsaysay Ave, Naga City',
    googleMapsUrl: 'https://maps.google.com/?q=13.6210,123.1945',
    photoUrl: undefined,
    likes: 88,
    createdBy: 'seed_admin',
    isSeeded: true,
    createdAt: Timestamp.now(),
  },
  {
    id: 'mock_016',
    name: "Lola Nena's Pandesal",
    categories: ['bakery'],
    description: 'Mainit na pandesal tuwing umaga. Kasama ang kape o tsokolate!',
    priceMin: 5,
    priceMax: 25,
    latitude: 13.6222,
    longitude: 123.1962,
    address: 'Peñafrancia Ave, Naga City',
    googleMapsUrl: 'https://maps.google.com/?q=13.6222,123.1962',
    photoUrl: undefined,
    likes: 73,
    createdBy: 'seed_admin',
    isSeeded: true,
    createdAt: Timestamp.now(),
  },
];
