export const strings = {
  en: {
    common: {
      priceTiers: {
        veryBudget: "Very Budget",
        affordable: "Affordable",
        moderate: "Moderate",
        expensive: "Expensive",
      }
    },
    addSpot: {
      title: "Add a Spot",
      locationStepTitle: "Pin Location",
      detailsStepTitle: "Add Details",
      searchPlaceholder: "Search location...",
      pinLocationButton: "Pin Location",
      openMapButton: "Open Map",
      nextButton: "Next",
      submitButton: "Add Spot",
      cancelButton: "Cancel",
      placeNamePlaceholder: "Place Name (e.g., Aling Lucing's Sisig)",
      cameraOption: "Take a Photo",
      galleryOption: "Choose from Gallery",
      categoryLabel: "Category",
      priceLabel: "Price Range",
      priceVeryBudget: "Very Budget (₱50-100)",
      priceAffordable: "Affordable (₱100-200)",
      priceModerate: "Moderate (₱200-350)",
      reviewPlaceholder: "What's good here?",
      uploadingLocation: "Getting location...",
      uploadingData: "Adding food spot...",
      successTitle: "Success!",
      successMessage: "Food spot added to your list.",
      errorTitle: "Oops!",
      errorNoImage: "Please add an image.",
      errorNoName: "Please enter a place name.",
      errorNoLocation: "Please pin a location.",
      imagePickerTitle: "Choose a Photo",
      imagePickerMessage: "Where do you want to get the photo?",
      imagePickerCancel: "Cancel",
      permissionDenied: "Permission denied",
      cameraPermissionMsg: "Camera permission is required to take photos.",
      galleryPermissionMsg: "Gallery permission is required to choose photos.",
      loginRequired: "Please sign in first.",
      tapMapError: "Tap the map to pin your location.",
      thanksTitle: "Salamat!",
      thanksMessage: "Your spot has been added. The community will love it!",
      okButton: "Done",
      genericError: "Something went wrong. Please try again.",
      cameraPromptText: "Take a picture of that delicious find!\n(optional)",
      placeNameLabel: "Place Name",
      placeNameHint: "e.g., Aling Nena's Silog",
      descriptionLabel: "Short Description",
      descriptionHint: "What makes this place special?",
      foodCategoryLabel: "Food Type",
      foodCategoryHint: "(can choose multiple)",
      priceRangeLabel: "Price (₱)",
      priceMinLabel: "Minimum",
      priceMaxLabel: "Maximum",
      mapInstruction:
        "Open the map and drag to your location. The pin stays in the center.",
      noPinnedLocation: "No location pinned yet",
      dragMapHint: "Drag map to pin location",
      mapCenterHint: "Hold still to confirm",
      addressLabel: "Street / Landmark",
      addressHint: "e.g., Near ADNU Gate (optional)",
      confirmButton: "Confirm",
    },
    home: {
      title: "Saan tayo kakain?",
      emptyStateTitle: "Wala pang listings dito",
      emptyStateDesc:
        "Maging lodi! Ikaw ang unang mag-add ng paborito mong kainan para dito.",
      emptyStateAction: "Mag-add ka!",
      showAllFilter: "🌍 Show Anywhere",
    },
    tabs: {
      home: "Home",
      map: "Mapa",
      randomizer: "Kahit Saan",
      profile: "Profile",
    },
    mapScreen: {
      title: "MAPA",
      subtitle: "Spots on the map",
      emptyDesc: "Kalma kapatid, pagod pa si Google Maps eh.",
      comingSoon: "COMING SOON",
      spotsCount: (n: number) => `${n} spot${n !== 1 ? "s" : ""} on map`,
      loadingSpots: "Searching for spots...",
      loadingLocation: "Finding your location...",
      filterFab: "Filter the Map",
      filterModalTitle: "Filter the Map",
      filterComingSoon: "Filters coming soon!",
    },
    profileScreen: {
      title: "Profile",
      emptyDesc: "Wait lang Yah, di pa keri ng Ferson.",
      comingSoon: "COMING SOON",
    },
    randomizerScreen: {
      title: "Randomizer",
      emptyDesc: "Wala pa munang randomizer idol.",
      comingSoon: "COMING SOON",
    },
    detailScreen: {
      loading: 'Loading...',
      notFound: "Sorry, we couldn't find this spot.",
      addPhotoTitle: 'Add Photo',
      addPhotoSource: 'Where do you want to get the photo?',
      cameraOption: 'Camera',
      galleryOption: 'Gallery',
      cancel: 'Cancel',
      uploadFailed: 'Upload failed. Please try again.',
      signInToPhoto: 'Sign in to add photos.',
      priceSurveyLabel: 'Presyo',
      priceSurveyTitle: 'Magkano daw?',
      priceSurveySubtitle: 'I-vote ang presyo ng spot na ito',
      priceSurveyNoVotes: 'Wala pang boto',
      priceSurveyGateHint: 'Na-try mo na ba? Mark it to vote! 🍽',
      photosLabel: 'Mga Larawan',
      directionsButton: 'Petiks Directions',
      wishlistButton: 'I-save sa Wishlist',
      wishlistDone: 'Na-save na!',
      triedButton: 'Na-try ko na!',
      triedDone: 'Na-try na!',
      shareButton: 'I-share sa tropa',
      shareMessage: 'Subukan mo na tong {{placeName}}! {{url}}',
      photoCount: '{{count}} photo{{s}}',
      noPhotos: 'Wala pa',
      priceSurveyCommunityVotes: 'Batay sa {{count}} boto ng komunidad',
    },
    loginScreen: {
      appName: "KainTayo",
      loginSubtitle: "Sign in to start",
      registerSubtitle: "Create an account",

      emailPlaceholder: "Email address",
      passwordPlaceholder: "Password",
      loginButton: "Sign in",
      registerButton: "Register",
      orText: "or",
      googleButton: "Sign in with Google",
      noAccountText: "No account yet? Register",
      hasAccountText: "Already have an account? Sign in",
      errorEmptyFields: "Please enter email and password!",
      errorEmailInUse: "This email is already in use.",
      errorWeakPassword: "Password must be at least 6 characters.",
      errorInvalidCreds: "Invalid email or password.",
      errorGeneric: "An error occurred. Please try again!",
      errorGoogle: "Failed to sign in with Google. Please try again!",
    },
    settings: {
      languageTitle: "Language",
      englishOption: "Taglish (Default)",
      tagalogOption: "Tagalog",
      logout: "Log out",
    },
    foodCard: {
      communityAdded: "Community Added ★",
      distanceAway: "km away",
      triedItYes: "Na-try Ko Na ✓",
      triedItNo: "Na-try mo na?",
    },
    spotCallout: {
      detailsButton: "Tap for details",
    },
  },
  tl: {
    common: {
      priceTiers: {
        veryBudget: "Sobrang Sulit",
        affordable: "Sakto Lang",
        moderate: "Medyo May Kamahalan",
        expensive: "Mahal",
      }
    },
    addSpot: {
      title: "Mag-Add ng Spot",
      locationStepTitle: "I-pin ang Lokasyon",
      detailsStepTitle: "Ilagay ang Detalye",
      searchPlaceholder: "Maghanap ng lokasyon...",
      pinLocationButton: "I-pin ang Lokasyon",
      openMapButton: "Buksan ang Mapa",
      nextButton: "Susunod",
      submitButton: "I-add ang Spot",
      cancelButton: "Kanselahin",
      placeNamePlaceholder: "Pangalan ng Lugar (hal. Aling Lucing's Sisig)",
      cameraOption: "Kumuha ng Litrato",
      galleryOption: "Pumili sa Gallery",
      categoryLabel: "Kategorya",
      priceLabel: "Presyo",
      priceVeryBudget: "Sobrang Sulit (₱50-100)",
      priceAffordable: "Sakto Lang (₱100-200)",
      priceModerate: "Medyo May Kamahalan (₱200-350)",
      reviewPlaceholder: "Anong masarap dito?",
      uploadingLocation: "Kinukuha ang lokasyon...",
      uploadingData: "Dinadagdag ang food spot...",
      successTitle: "Tagumpay!",
      successMessage: "Nai-add na ang food spot sa iyong listahan.",
      errorTitle: "Teka lang!",
      errorNoImage: "Mangyaring maglagay ng litrato.",
      errorNoName: "Mangyaring ilagay ang pangalan ng lugar.",
      errorNoLocation: "Mangyaring i-pin ang lokasyon.",
      imagePickerTitle: "Pumili ng Larawan",
      imagePickerMessage: "Saan mo kukunin ang litrato?",
      imagePickerCancel: "Huwag na",
      permissionDenied: "Permission denied",
      cameraPermissionMsg:
        "Kailangan ang camera permission para kumuha ng litrato.",
      galleryPermissionMsg:
        "Kailangan ang gallery permission para pumili ng litrato.",
      loginRequired: "Kailangan mag-login muna. Please sign in first.",
      tapMapError: "I-tap ang mapa para i-pin ang lokasyon mo.",
      thanksTitle: "Salamat!",
      thanksMessage: "Na-add na ang spot mo. Malaki ang tulong mo!",
      okButton: "OK",
      genericError: "May nangyaring mali. Subukan ulit.",
      cameraPromptText: "Pikturan ang masarap na find!\n(optional)",
      placeNameLabel: "Pangalan ng Kainan",
      placeNameHint: "hal. Aling Nena's Silog",
      descriptionLabel: "Maikling Paglalarawan",
      descriptionHint: "Anong specialty nila? Bakit paborito mo?",
      foodCategoryLabel: "Klase ng Pagkain",
      foodCategoryHint: "(puwedeng marami)",
      priceRangeLabel: "Presyo (₱)",
      priceMinLabel: "Minimum",
      priceMaxLabel: "Maximum",
      mapInstruction:
        "I-tap ang button sa ibaba para buksan ang buong mapa at i-drop ang pin.",
      noPinnedLocation: "Wala pang pinned location",
      dragMapHint: "I-drag ang mapa para i-pin ang lokasyon",
      mapCenterHint: "Sandali lang para ma-confirm",
      addressLabel: "Kalye / Landmark",
      addressHint: "hal. Malapit sa ADNU Gate (optional)",
      confirmButton: "Kumpirmahin",
    },
    home: {
      title: "Saan tayo kakain?",
      emptyStateTitle: "Wala pang listings dito",
      emptyStateDesc:
        "Maging lodi! Ikaw ang unang mag-add ng paborito mong kainan para dito.",
      emptyStateAction: "Mag-add ka!",
      showAllFilter: "🌍 Kahit Saan",
    },
    tabs: {
      home: "Home",
      map: "Mapa",
      randomizer: "Kahit Saan",
      profile: "Profile",
    },
    mapScreen: {
      title: "MAPA",
      subtitle: "Mga kainan sa mapa",
      emptyDesc: "Kalma kapatid, pagod pa si Google Maps eh.",
      comingSoon: "COMING SOON",
      spotsCount: (n: number) => `${n} kainan sa mapa`,
      loadingSpots: "Hinahanap ang mga kainan...",
      loadingLocation: "Hinahanap ang iyong lokasyon...",
      filterFab: "Salain ang Mapa",
      filterModalTitle: "I-filter ang Mapa",
      filterComingSoon: "Malapit na ang mga filter!",
    },
    profileScreen: {
      title: "Profile",
      emptyDesc: "Wait lang Yah, di pa keri ng Ferson.",
      comingSoon: "COMING SOON",
    },
    randomizerScreen: {
      title: "Randomizer",
      emptyDesc: "Wala pa munang randomizer idol.",
      comingSoon: "COMING SOON",
    },
    detailScreen: {
      loading: 'Hintayin mo...',
      notFound: 'Ay, wala na yata. Baka tanggal na yung spot.',
      addPhotoTitle: 'Mag-add ng Larawan',
      addPhotoSource: 'Saan kukuha ng larawan?',
      cameraOption: 'Camera',
      galleryOption: 'Gallery',
      cancel: 'Huwag na',
      uploadFailed: 'Hindi na-upload. Subukan ulit.',
      signInToPhoto: 'Mag-sign in para mag-add ng photos.',
      priceSurveyLabel: 'Presyo',
      priceSurveyTitle: 'Magkano daw?',
      priceSurveySubtitle: 'I-vote ang presyo ng spot na ito',
      priceSurveyNoVotes: 'Wala pang boto',
      priceSurveyGateHint: 'Na-try mo na ba? I-mark para makaboto! 🍽',
      photosLabel: 'Mga Larawan',
      directionsButton: 'Petiks Directions',
      wishlistButton: 'I-save sa Wishlist',
      wishlistDone: 'Na-save na!',
      triedButton: 'Na-try ko na!',
      triedDone: 'Na-try na!',
      shareButton: 'I-share sa tropa',
      shareMessage: 'Subukan mo na itong {{placeName}}! {{url}}',
      photoCount: '{{count}} larawan',
      noPhotos: 'Wala pa',
      priceSurveyCommunityVotes: 'Batay sa {{count}} boto ng komunidad',
    },
    loginScreen: {
      appName: "KainTayo",
      loginSubtitle: "Mag-login para magsimula",
      registerSubtitle: "Gumawa ng account",
      emailPlaceholder: "Email address",
      passwordPlaceholder: "Password",
      loginButton: "Mag-login",
      registerButton: "Mag-register",
      orText: "o kaya",
      googleButton: "Mag-login gamit ang Google",
      noAccountText: "Wala pang account? Mag-register",
      hasAccountText: "May account na? Mag-login",
      errorEmptyFields: "Lagyan mo ng email at password!",
      errorEmailInUse: "Ginagamit na ang email na ito.",
      errorWeakPassword: "Dapat 6 characters pataas ang password.",
      errorInvalidCreds: "Mali ang email o password.",
      errorGeneric: "May error na nangyari. Subukan ulit!",
      errorGoogle: "Hindi makapag-login sa Google. Subukan ulit!",
    },
    settings: {
      languageTitle: "Wika (Language)",
      englishOption: "Taglish (Default)",
      tagalogOption: "Tagalog",
      logout: "Mag-log out",
    },
    foodCard: {
      communityAdded: "Dagdag ng Komunidad ★",
      distanceAway: "km ang layo",
      triedItYes: "Na-try Ko Na ✓",
      triedItNo: "Nasubukan mo na?",
    },
    spotCallout: {
      detailsButton: "I-tap para sa detalye",
    },
  },
};

export type LanguageOption = keyof typeof strings;
export type AppStrings = (typeof strings)["en"];
